/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControlePessoa;
import static groovy.sql.Sql.resultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Aelcio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ControlePessoa controlpessoa = new ControlePessoa();

    public Principal() {
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuCadCliente = new javax.swing.JMenuItem();
        jMenuCadCidade = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuRegistros = new javax.swing.JMenu();
        jMenuAtendimento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMRelClientes = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCadastros.setText("Cadastros");

        jMenuCadCliente.setText("Clientes");
        jMenuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadCliente);

        jMenuCadCidade.setText("Cidades");
        jMenuCadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCidadeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadCidade);

        jMenuSair.setText("Sair");
        jMenuCadastros.add(jMenuSair);

        jMenuBar1.add(jMenuCadastros);

        jMenuRegistros.setText("Registros");

        jMenuAtendimento.setText("Atendimentos");
        jMenuAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAtendimentoActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuAtendimento);

        jMenuBar1.add(jMenuRegistros);

        jMenu2.setText("Relatórios");

        jMRelClientes.setText("Clientes");
        jMRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRelClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMRelClientes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadClienteActionPerformed
        new CadCliente().setVisible(true);
    }//GEN-LAST:event_jMenuCadClienteActionPerformed

    private void jMenuCadCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCidadeActionPerformed
        new CadCidade().setVisible(true);
    }//GEN-LAST:event_jMenuCadCidadeActionPerformed

    private void jMenuAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAtendimentoActionPerformed
        new CadAtendimentos().setVisible(true);
    }//GEN-LAST:event_jMenuAtendimentoActionPerformed

    private void jMRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRelClientesActionPerformed
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(controlpessoa.consultageral());
            JasperPrint jpPrint = JasperFillManager.fillReport("Relatorios/RelClientes.jasper", new HashMap(), resultset);
            JasperViewer jv = new JasperViewer(jpPrint , false);
            jv.setVisible(true);
            jv.toFront();
        } catch (Exception ex) {    
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório" + ex.getMessage());

        }
    }//GEN-LAST:event_jMRelClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMRelClientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadCidade;
    private javax.swing.JMenuItem jMenuCadCliente;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuRegistros;
    private javax.swing.JMenuItem jMenuSair;
    // End of variables declaration//GEN-END:variables
}
